#!/usr/bin/python

import sys
import argparse

import yacite.command.dummy
import yacite.command.read
import yacite.command.merge
import yacite.command.filter
import yacite.command.execc
import yacite.command.render
import yacite.command.append
import yacite.command.unappend
import yacite.command.rewrite
import yacite.command.sort

c_map={
    "dummy":yacite.command.dummy.Dummy,
    "read":yacite.command.read.Read,
    "merge":yacite.command.merge.Merge,
    "filter":yacite.command.filter.Filter,
    "exec":yacite.command.execc.Exec,
    "render":yacite.command.render.Render,
    "append":yacite.command.append.Append,
    "unappend":yacite.command.unappend.Unappend,
    "rewrite":yacite.command.rewrite.Rewrite,
    "sort":yacite.command.sort.Sort,
}

parse=argparse.ArgumentParser()
subparsers=parse.add_subparsers(dest="command",help="The yacite subcommand you want to run")
for cmd in c_map:
    cmd_class=c_map[cmd]
    subpar=subparsers.add_parser(cmd,help=cmd_class.help)
    cmd_class.add_arguments(subpar)
ns=parse.parse_args()
command=c_map[ns.command](ns)
command.execute()





